version: "3"

# Network
networks:
  back-end:
    driver: "bridge"
  front-end:
    driver: "bridge"

volumes:
  db-data:
    {}
    # driver: "local"
    # driver_opts:
    #   device: "/dev/sdb"
    #   type: "ext4"

services:
  # Container PostgreSQL
  db:
    container_name: db-postgres
    image: "postgres:12"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    networks:
      - back-end
    volumes:
      - db-data:/var/lib/postgresql/data

  # Container NodeJS
  server:
    container_name: nodejs
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
    networks:
      - back-end
    depends_on:
      - db

  # Container ReactJS
  client:
    container_name: reactjs
    build:
      context: ./client
      dockerfile: Dockerfile
    hostname: localhost
    ports:
      - "3000:3000"
    restart: always
    networks:
      - front-end
